[修复报错];[错误缘由] 若一个动作含有多个修改源码文本行为, 则修改1 可能印象修改2 的执行背景,从而导致修改2报错.  [遵守规则] 一个动作必须只能含有一个修改源码文本行为;
修复报错:

InvalidOperationError: Attempted to get information from a node that was removed or forgotten.